### ISSUE TITLE
Unmarshalling relationships with null data bodies throws an exception

### ISSUE THREAD

**Issue by aldridmc-gio** [DataDog/jsonapi#17]
**Describe the bug**

When unmarshalling jsonapi data with relationships including null data bodies an exception is thrown:

`body is not a json:api representation of *model.SomeModel`

The following is an example relationship that causes this behaviour.

```
"invoice": {
    "links": {
        "self": "https://api.example.io/v1/invoices/123456789/relationships/invoice",
        "related": "https://api.example.io/v1/invoices/123456789/invoice"
    },
    "data": null
},

```

**Expected behavior**

Relationship jsonapi such as above is apparently valid according to the spec and therefore should simply be ignored by the code. This was proved by simply removing the offending jsonapi relationships from the source json which allowed for a problem free and correct unmarshalling of the whole json.

**Comment by kpurdon** [comment]
Thanks for the report. We’ll take a look.
