### ISSUE TITLE
Options ignored when marshaling nil value

### ISSUE THREAD

**Issue by leg100** [DataDog/jsonapi#30]
**Describe the bug**

Marshaling a nil value ignores marshaling options.

**Expected behavior**

I would expect marshaling to apply marshaling options even with a nil value.

**Links**

https://go.dev/play/p/dtjasHU3_5T

**Additional context**

The same bug occurs when marshaling a nil slice.

**Comment by kpurdon** [comment]
👍🏻 thanks for the report, we'll look into this soon. Feel free to open a PR if you'd like too.
