### ISSUE TITLE
Unmarshalling single object with relationship with no data attribute throws exception

### ISSUE THREAD

**Issue by aldridmc-gio** [DataDog/jsonapi#34]
**Describe the bug**

Introduced in 0.72 it seems that there is an issue unmarshalling objects (non-array) with relationships that **do not** contain a data attribute

Here is an example code snippet causing the unmarshalling error:

```
package main

import (
	"fmt"

	"github.com/DataDog/jsonapi"
)

func main() {
	body := `{"data":{"id":"1","type":"articles","attributes":{"title":"Hello World"},"relationships":{"author":{"links":{"self":"https://localhost/article/1/relationships/author","related":"https://localhost/article/1/author"}}}}}`

	type Author struct {
		ID   string `jsonapi:"primary,authors"`
		Name string `jsonapi:"attribute" json:"name"`
	}

	type Article struct {
		ID     string  `jsonapi:"primary,articles"`
		Title  string  `jsonapi:"attribute" json:"title"`
		Author *Author `jsonapi:"relationship" json:"author"`
	}

	var a Article
	err := jsonapi.Unmarshal([]byte(body), &a)
	if err != nil {
		panic(err)
	}

	fmt.Printf("%+v", &a)
}
```

The result is an exception:

`panic: document is missing a required top-level or relationship-level data member
`

**Expected behavior**

Unmarshalling should not throw an exception.

**Comment by DQSevilla** [comment]
Hello, thanks for reporting! We'll take a look at this issue soon. Feel free to open a PR if you'd like to.

**Comment by aldridmc-gio** [comment]
Hi, I just tested the above code with 0.7.2 and can still reproduce the panic so this still isn't resolve.
